[dask] Support type hints.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -171,10 +171,19 @@ jobs:
         architecture: 'x64'
     - name: Install Python packages
       run: |
-        python -m pip install wheel setuptools mypy
+        python -m pip install wheel setuptools mypy dask[complete] distributed
     - name: Run mypy
       run: |
-        cd python-package && mypy . || true
+        cd python-package
+        # dask is required to pass, others are not
+        printf '\n\n mypy start: --- Following errors until end mark are not required to fix ------\n\n'
+
+        mypy . || true
+
+        printf '\n\n mypy end:  --- Above errors are not required to fix --------------------------\n\n'
+
+        mypy ./xgboost/dask.py ../tests/python/test_with_dask.py --follow-imports=silent
+        mypy ../tests/python-gpu/test_gpu_with_dask.py --follow-imports=silent
 
   doxygen:
     runs-on: ubuntu-latest
